// public/performance.json read as data, for the components and markdown blocks
// that show speed (RunsEverywhere, XrtChip, the ```perf block). The file is
// generated by the performance emitter; nothing here types a number. Read with
// fs at build time so Node scripts, the markdown pipeline and pages share it.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { formatMultiple } from "./format-multiple.ts";
import { NO_GPU } from "../data/perf-groups.ts";

export type PerfModel = "essence-2" | "expression-2";
export const PERF_MODELS: { id: PerfModel; name: string }[] = [
  { id: "essence-2", name: "Essence 2" },
  { id: "expression-2", name: "Expression 2" },
];

export interface PerfCell {
  x_realtime: number;
  fps: number;
  release: string;
  measured_on: string;
  realtime: boolean;
}
export interface PerfRowData {
  id: string;
  label: string;
  hardware: string;
  published: boolean;
  sustained: boolean;
  cells: Partial<Record<PerfModel, PerfCell | null>>;
}
interface PerfFile { generated: string; page: string; rows: PerfRowData[] }

let cache: PerfFile | null = null;
export function perfData(): PerfFile {
  cache ??= JSON.parse(readFileSync(join(process.cwd(), "public/performance.json"), "utf8")) as PerfFile;
  return cache;
}

/** One published row by id; throws on an unknown or unpublished id, so a page
 *  can never draw a number the record does not hold. */
export function perfRow(id: string): PerfRowData {
  const r = perfData().rows.find((x) => x.id === id);
  if (!r) throw new Error(`performance.json has no row "${id}"`);
  if (!r.published) throw new Error(`performance.json row "${id}" is not published`);
  return r;
}

export const noGpu = (id: string) => NO_GPU.includes(id);

/** The chip text and its detail line for one cell, or null when not measured. */
export function perfCell(id: string, model: PerfModel): { x: string; detail: string; realtime: boolean } | null {
  const r = perfRow(id);
  const c = r.cells[model];
  if (!c) return null;
  const where = noGpu(id) ? `${r.hardware}, CPU only (no GPU)` : r.hardware;
  const held = r.sustained ? " · held 10 min" : "";
  return {
    x: formatMultiple(c.x_realtime),
    detail: `${where} · ${c.release}${held} · measured ${c.measured_on}`,
    realtime: c.x_realtime >= 1,
  };
}

/** The label a reader sees for a row: the platform half of the emitter's label. */
export function rowName(id: string): string {
  const r = perfRow(id);
  return r.label.replace(/\s*·\s*held 10 min$/, "");
}
